name: mapbox_nigeria_app
description: A Flutter app showing Mapbox with Nigerian locations.
publish_to: 'none'

version: 4.0.0+4

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The official, modern Mapbox package
  mapbox_maps_flutter: ^2.0.0
  
  # For getting the device's GPS location
  geolocator: ^14.0.2
  
  # HTTP requests for API calls
  http: ^1.2.0
  
  # For weather data
  weather: ^3.1.1
  
  # For permission handling
  permission_handler: ^11.3.0
  
  # For JSON parsing
  json_annotation: ^4.8.1
  
  # For state management
  provider: ^6.1.1
  
  # For formatting
  intl: ^0.19.0
  
  # Text-to-speech for spoken directions
  flutter_tts: ^4.2.0
  
  # For polyline drawing
  turf: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true