name: mapbox_nigeria_app
description: A Flutter app showing Mapbox with Nigerian locations.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The official, modern Mapbox package
  mapbox_maps_flutter: ^2.0.0
  
  # For getting the device's GPS location
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true